# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('bought_id', models.AutoField(primary_key=True, serialize=False)),
                ('buytime', models.DateTimeField()),
                ('endtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bought',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ForumResponse',
            fields=[
                ('contain', models.CharField(blank=True, max_length=100, null=True)),
                ('init_time', models.CharField(max_length=45)),
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'forum_response',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('purchase_times', models.IntegerField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_manual', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales',
                'managed': True,
            },
        ),
    ]
