# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bought',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='forumresponse',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'managed': False},
        ),
    ]
