# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('last_save_code', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
                ('init_time', models.DateTimeField()),
                ('notes', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'code',
                'managed': True,
            },
        ),
    ]
