# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0002_auto_20170327_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'managed': True},
        ),
    ]
