# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('contain', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
    ]
