# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrypoint', '0002_auto_20170327_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True},
        ),
    ]
